from django.urls import path
from rest_framework import routers

from notes.views import NotesView, NotesItemView, AutoGeneratedNoteView, AuthViewSet


router = routers.DefaultRouter(trailing_slash=False)
router.register('api/auth', AuthViewSet, basename='auth')

urlpatterns = [
    path('api/notes/', NotesView.as_view(), name='notes'),
    path('api/notes/<int:pk>', NotesItemView.as_view(), name='notes_item'),
    path('api/notes/autogenerate', AutoGeneratedNoteView.as_view(), name='autogenerated_note')
]
urlpatterns += router.urls
