from django.urls import path

from notes.views import NotesView, NotesItemView, AutoGeneratedNoteView


urlpatterns = [
    path('notes/', NotesView.as_view(), name='notes'),
    path('notes/<int:pk>', NotesItemView.as_view(), name='notes_item'),
    path('notes/<int:pk>/autogenerate', AutoGeneratedNoteView.as_view(), name='autogenerated_note')
]
