from django.urls import path

from notes.views import NotesView, NotesItemView, AutoGeneratedNoteView

urlpatterns = [
    path('', NotesView.as_view(), name='notes'),
    path('<int:pk>', NotesItemView.as_view(), name='notes_item'),
    path('autogenerate', AutoGeneratedNoteView.as_view(), name='autogenerated_note'),
]
