from rest_framework import status
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.views import APIView

from notes import serializers
from notes.models import Note
from notes.utils import get_bacon_ipsum_content


class NotesView(APIView):
    permission_classes = [IsAuthenticated, ]

    def get(self, request):
        notes = Note.objects.filter(user=request.user.id)
        serializer = serializers.NoteSerializer(notes, many=True)
        return Response({'notes': serializer.data}, status=status.HTTP_200_OK)

    def post(self, request):
        data = {
            'title': request.data.get('title'),
            'content': request.data.get('content'),
            'user': request.user.id,
        }
        serializer = serializers.NoteSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response({'note': serializer.data}, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class NotesItemView(APIView):
    permission_classes = [IsAuthenticated, ]

    def get(self, request, pk):
        try:
            note = Note.objects.get(pk=pk, user=request.user.id)
        except Note.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

        serializer = serializers.NoteSerializer(note)
        return Response({'note': serializer.data}, status=status.HTTP_200_OK)

    def put(self, request, pk):
        try:
            note = Note.objects.get(pk=pk, user=request.user.id)
        except Note.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

        request.data['user'] = request.user.id
        serializer = serializers.NoteSerializer(note, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response({'note': serializer.data}, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        try:
            note = Note.objects.get(pk=pk, user=request.user.id)
        except Note.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

        note.delete()
        return Response(status=status.HTTP_200_OK)


class AutoGeneratedNoteView(APIView):
    def post(self, request):

        request.data['title'] = 'Bacon Note'
        request.data['content'] = get_bacon_ipsum_content()
        request.data['user'] = request.user.id

        return NotesView.post(NotesView.as_view(), request=request)
